Argument Resolution Refactoring
delira-dev/delira pull request #184
Opened 2019-08-21 08:05 UTC by justusschock

Fixes #180 once it's done.

Tests have not yet been updated. Before doing this, a feedback on the general structure would be nice

2019-08-25 09:24 UTC, mibaumgartner requested changes
I reviewed the pytorch experiment and the baseexperiment (most of the comments should apply to the other experiments, too). Really digging the new argument structure, much more intuitive. Added a bit more comment than usual because this is a good opportunity to improve the general interface of delira.

Further considerations include:
1. Where is the batchsize determined. After some thought, I really liked the idea of you to use the batchsize from the datamanager.

2. Where is a good point to mention which arguments need to be passed by the parameters object | datamanager | experiment ? (the experiment args are obvious but the parameters and datamangers aren't)

3. The notebooks should be updated accordingly, too. (This should probably happen after https://github.com/delira-dev/delira/pull/182) 

4. Do we want to include typings for the experiment interfaces? (I think this would be the right to do that)

2019-08-25 09:24 UTC, mibaumgartner commented on delira/training/backends/torch/experiment.py
>              additional keyword arguments
Please mention where the kwargs are going.

2019-08-25 09:24 UTC, mibaumgartner commented on delira/training/backends/torch/experiment.py
> +        Parameters
Blank line between description and parameters missing.

2019-08-25 09:24 UTC, mibaumgartner commented on delira/training/backends/torch/experiment.py
> +        model : :class:`AbstractNetwork`
It would be great if the order of the argument descriptions is the same as the order in the call (make life a little bit easier ^^ )

2019-08-25 09:24 UTC, mibaumgartner commented on delira/training/backends/torch/experiment.py
> +        **kwargs :
Please mention where the kwargs are going.

2019-08-25 09:24 UTC, mibaumgartner commented on delira/training/backends/torch/experiment.py
> +        prepare_batch : function
Comment that the default will be set to the model's `prepare_batch` function

2019-08-25 09:24 UTC, mibaumgartner commented on delira/training/backends/torch/experiment.py
>              additional keyword arguments
There are no kwargs in the function call.

2019-08-26 22:42 UTC, justusschock commented
All the changes you requested are making sense to me, so I'll add them later on.

Regarding your considerations:

1. The batchsize is only determined during initialization of the datamanager, so this does not involve this part (Of course one could use the parameters class to temporarily store this value too).

2. Probably inside our basic `delira` tutorial, as well as in the desciption of our `BaseExperiment`?

3. We should definitely do this. I would prefer to integrate it into #182 (after this PR is merged)instead of adding it as a separate PR.

4. I would not add the typing here, but do it, while we add stub files (and check the whole project's typing)

2020-02-06 09:15 UTC, closed without merging