Added test function to experiment
delira-dev/delira pull request #42
Opened 2019-01-22 10:39 UTC by micha2

CC: @justusschock @ORippler

2019-01-22 13:08 UTC, justusschock reviewed
I don't see any problems right now. We might have to refactor this, once #17 is finished, but the changes should be minor, so if @ORippler agrees, this could be a workaround to go.

2019-01-22 15:31 UTC, justusschock requested changes

2019-01-22 15:31 UTC, justusschock commented on delira/training/experiment.py
> +        def test(self,
Add abstract method in `AbstractExperiment` to ensure consistent API

2019-01-22 15:40 UTC, justusschock approved these changes

2019-01-24 16:15 UTC, ORippler approved these changes

2019-01-25 08:48 UTC, merged